### ISSUE TITLE
Allow text after [Error

### ISSUE THREAD

**Issue by adrianiftode** [ilhan-mstf/colorize_cloudwatch_logs#9]
We are inserting some information in the tag itself, so I wonder if you could consider an error what includes `[Error` and not `[Error]`

![image](https://user-images.githubusercontent.com/13752939/72083378-65dea100-330a-11ea-8f45-9f31fec5f333.png)

**Comment by ilhan-mstf** [comment]
Thank you,
It seems possible. This weekend I can work on it.

**Comment by ilhan-mstf** [comment]
![Screenshot from 2020-01-13 00-09-19](https://user-images.githubusercontent.com/968651/72225654-faf6c980-3598-11ea-9860-a60e2b375d42.png)
Is this ok? (Please look at the "[Error bla bla bla" line)

**Comment by adrianiftode** [comment]
I just made a quick test. Is not working with `[Error` at all because `includes` seems to be case sensitive.

**Comment by ilhan-mstf** [comment]
I didn't release it yet. Screenshot is from my local. Therefore it is normal that you didn't see it in your test. I recommend you to check screenshot in the previous comment. Thanks...

**Comment by adrianiftode** [comment]
Looks good to me, thank you for your efforts

lun., 13 ian. 2020, 19:47 Mustafa İlhan <notifications@github.com> a scris:

**Comment by adrianiftode** [comment]
Looks great!
